---
- name: Quest dari rifqi, partisi disk
  hosts: all
  become: true
  tasks:
    - name: Buat partisi di disk /dev/vdb
      parted:
        device: /dev/vdb
        number: 1
        fs_type: ext4
        part_start: 1500MiB

    - name: Mount an NFS volume
        ansible.posix.mount:
        src: /dev/vdb1
        path: /mnt/vdb1_ygy
        state: mounted
        fstype: ext4